# Analisis Tingkat Churn Player Game "Gacha"
Tujuan : menganalisis kemungkinan player akan "churn".

## 1. Overview

In [26]:
import pandas as pd

df = pd.read_csv("player-dataset.csv")
df.head()

,user_id,week,session_time,device_class,avg_fps,total_pulls,ssr_obtained,got_target,story_progress,churn
0,1,0,2.80,medium,44.46,290,4,0,30.15,1
1,1,1,2.97,medium,42.98,290,4,0,30.15,1
2,1,2,2.82,medium,42.39,290,4,0,30.15,1
3,1,3,2.61,medium,41.62,290,4,0,30.15,1
4,1,4,3.05,medium,42.67,290,4,0,30.15,1

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   user_id         800 non-null    int64
 1   week            800 non-null    int64
 2   session_time    800 non-null    float64
 3   device_class    800 non-null    object
 4   avg_fps         800 non-null    float64
 5   total_pulls     800 non-null    int64
 6   ssr_obtained    800 non-null    int64
 7   got_target      800 non-null    int64
 8   story_progress  800 non-null    float64
 9   churn           800 non-null    int64
dtypes: float64(3), int64(6), object(1)
memory usage: 62.6+ KB

In [28]:
df.describe()

,user_id,week,session_time,avg_fps,total_pulls,ssr_obtained,got_target,story_progress,churn
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,50.500000,3.500000,4.299900,35.337888,151.500000,2.430000,0.270000,49.452500,0.630000
std,28.884128,2.292721,2.115579,11.436635,89.031783,1.505966,0.444237,20.627481,0.483106
min,1.000000,0.000000,1.130000,11.810000,0.000000,0.000000,0.000000,7.620000,0.000000
25%,25.750000,1.750000,2.710000,26.347500,80.000000,1.000000,0.000000,33.547500,0.000000
50%,50.500000,3.500000,3.980000,35.350000,150.000000,2.000000,0.000000,47.775000,1.000000
75%,75.250000,5.250000,5.452500,43.262500,230.000000,4.000000,1.000000,62.570000,1.000000
max,100.000000,7.000000,14.210000,60.960000,300.000000,5.000000,1.000000,98.290000,1.000000

## 2. Distribusi

In [29]:
df["churn"].value_counts()

churn
1    504
0    296
Name: count, dtype: int64

Distribusi menunjukkan jumlah player yang churn lebih banyak dibandingkan yang bertahan. Hal ini mengindikasikan bahwa dalam simulasi ini, kondisi yang memicu churn cukup dominan, sehingga dataset memiliki kecenderungan churn yang tinggi.

## 3. Analisis

### 3.1 Session Time

In [30]:
df.groupby("churn")["session_time"].mean()

churn
0    5.452365
1    3.623056
Name: session_time, dtype: float64

Player yang churn memiliki rata-rata session time yang lebih rendah dibandingkan player yang tidak churn. Hal ini menunjukkan bahwa tingkat engagement (waktu bermain) merupakan indikator kuat terhadap kemungkinan churn. Penurunan aktivitas bermain dapat menjadi sinyal awal bahwa player mulai kehilangan minat.

### 3.2 FPS / Hardware

In [31]:
df.groupby("churn")["avg_fps"].mean()

churn
0    40.110608
1    32.534861
Name: avg_fps, dtype: float64

Player yang churn cenderung memiliki average FPS yang lebih rendah. Hal ini menunjukkan bahwa performa device dan kenyamanan bermain memiliki pengaruh terhadap retensi player. Pengalaman bermain yang kurang optimal dapat menurunkan durasi bermain, yang pada akhirnya meningkatkan kemungkinan churn.

### 3.3 Pulls and SSR  Obtained

In [36]:
df.groupby("churn")[["total_pulls", "ssr_obtained", "got_target"]].mean()

       total_pulls  ssr_obtained  got_target
churn
0       161.081081      2.027027    0.459459
1       145.873016      2.666667    0.158730

Player yang churn menunjukkan jumlah SSR yang relatif lebih tinggi dengan total pull yang lebih sedikit, namun memiliki tingkat keberhasilan mendapatkan karakter target yang lebih rendah. Hal ini mengindikasikan bahwa kepuasan pemain tidak hanya ditentukan oleh jumlah SSR yang diperoleh, tetapi oleh relevansi karakter tersebut terhadap preferensi pemain. Ketidakberhasilan mendapatkan karakter incaran dapat menimbulkan frustrasi, meskipun secara kuantitas hasil gacha terlihat baik.

### 3.4 Story Progress

In [33]:
df.groupby("churn")["story_progress"].mean()

churn
0    47.028108
1    50.876349
Name: story_progress, dtype: float64

Player yang churn memiliki story progress yang sedikit lebih tinggi. Hal ini menunjukkan bahwa player yang sudah mencapai tahap lebih lanjut (mendekati endgame) cenderung mengalami penurunan minat, terutama jika tidak diimbangi dengan konten baru atau reward yang cukup. Kondisi ini dapat menyebabkan pemain merasa tidak memiliki tujuan lanjutan, sehingga meningkatkan kemungkinan churn.

### 3.5 Trend Session Time

In [39]:
df.groupby("week")["session_time"].mean()

week
0    4.6985
1    4.5926
2    4.4039
3    4.2498
4    4.2689
5    4.1562
6    3.9942
7    4.0351
Name: session_time, dtype: float64

Rata-rata session time menunjukkan tren menurun seiring waktu dalam periode 8 minggu. Hal ini mengindikasikan adanya penurunan engagement secara bertahap, yang merupakan pola umum sebelum terjadinya churn. Penurunan aktivitas ini dapat menjadi indikator awal untuk mendeteksi player yang berpotensi berhenti bermain.

## 4. Insight and Conclusion

Berdasarkan hasil analisis, terdapat beberapa faktor utama yang mempengaruhi kemungkinan churn pada player game gacha:

- Engagement (Session Time) : 
  Waktu bermain merupakan indikator paling kuat. Player dengan durasi bermain rendah dan tren aktivitas yang menurun memiliki kemungkinan churn yang lebih tinggi
- User Experience (Hardware / FPS) :
  Performa device berpengaruh terhadap kenyamanan bermain. FPS yang rendah dapat menurunkan pengalaman bermain dan secara tidak langsung mengurangi durasi bermain, yang meningkatkan risiko churn. :
- Gacha Satisfaction (Target vs Quantity) :
  Kepuasan player tidak ditentukan oleh jumlah SSR yang diperoleh, tetapi oleh keberhasilan mendapatkan karakter target. Player yang tidak mendapatkan karakter yang diinginkan cenderung mengalami frustrasi dan lebih berpotensi churn.
- Progression (Story / Endgame) :
  Player yang sudah mencapai tahap lanjut (endgame) cenderung mengalami penurunan motivasi jika tidak tersedia konten atau reward yang cukup. Hal ini dapat menyebabkan churn meskipun progress permainan sudah tinggi.

Secara keseluruhan, churn dipengaruhi oleh kombinasi antara engagement, pengalaman bermain, kepuasan reward, dan progres permainan, bukan hanya satu faktor tunggal.

Analisis ini dilakukan pada data simulasi, sehingga hubungan antar variabel dibentuk berdasarkan asumsi tertentu. Namun, pendekatan ini mencerminkan bagaimana proses analisis data dilakukan dalam kasus nyata.